### ISSUE TITLE
OreDict not working

### ISSUE THREAD

**Issue by DoktorAerzt** [CAS-ual-TY/INeedThemOres#1]
Hello, 

is it intended that there are no oredicts for the forge group? Like forge:ingot/copper?

**Comment by CAS-ual-TY** [comment]
https://github.com/CAS-ual-TY/INeedThemOres/tree/master/src/main/resources/data/ineedthemores/tags
Isnt that how you do tags? Sorry first timer on tags

**Comment by CAS-ual-TY** [comment]
So I have to put forge as namespace?

**Comment by DoktorAerzt** [comment]
Maybe, i dont know. The problem is, when i add the tag with crafttweaker and no other mod create the tag befor hand. Then mods like IronChest can´t use it. 

In CraftTweaker i create the tag and add the item like so: 

<tag:forge:ingots/copper>.createItemTag();
<tag:forge:ingots/copper>.addItems([<item:ineedthemores:copper_ingot>]);

**Comment by DoktorAerzt** [comment]
i can´t follow up how create is doing it 	

https://github.com/Creators-of-Create/Create/blob/7374866293e9c36e3e03cc779ba6decb0defcd46/src/main/java/com/simibubi/create/AllItems.java#L74

**Comment by DoktorAerzt** [comment]
I know how it works and how we get it. 

just Copy every file from src/main/resources/data/ineedthemores/tags 
to src/main/resources/data/forge/tags 

When you copy, then you get both tags. 
Don´t change the files.
