### ISSUE TITLE
Add Zinc

### ISSUE THREAD

**Issue by DoktorAerzt** [CAS-ual-TY/INeedThemOres#2]
Could you please add Zinc as Ore? 

I need it for Create witch is not ready for 1.15.1

**Comment by CAS-ual-TY** [comment]
Alright. Will do
Any spawn rates I should go for? How rare is it?

**Comment by DoktorAerzt** [comment]
I think close to tin should be good. I just changed tries_amount = 20 to 9
`
	#The Size of eich Veign  

	#Range: 0 ~ 100  

	veign_size = 7  

	#Top Edge for Overworld Generation  

	#Range: 0 ~ 255  

	top = 48  

	#Bottom Edge for Overworld Generation  

	#Range: 0 ~ 255  

	bottom = 16  

	#Amount of Tries per Chunk to generate a Veign  

	#Range: 0 ~ 100  

	tries_amount = 9  

	#0 = Wood, 1 = Stone, 2 = Iron, 3 = Diamond, 4+ = Modded Items (See each individual Mod) 
 
	#Range: 0 ~ 100  

	harvest_level = 1  

	#Enable Generation in the Overworld  

	enabled = true  

`
